build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false

complexity:
  active: true
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 7
  LongMethod:
    active: true
    threshold: 100
    excludes: ['**/ui/**', '**/*Screen.kt', '**/*UI.kt', '**/*Badge.kt', '**/*Card.kt']
  CyclomaticComplexMethod:
    active: true
    threshold: 15

naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated: ['Composable']
  ClassNaming:
    active: true
  PackageNaming:
    active: true
  VariableNaming:
    active: true

style:
  active: true
  MaxLineLength:
    active: true
    maxLineLength: 120
  MagicNumber:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/Color.kt', '**/Theme.kt', '**/*UI.kt', '**/*Screen.kt', '**/*Badge.kt']
    ignoreNumbers: ['-1', '0', '1', '2', '25', '50', '75', '100', '1000']
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreAnnotation: true
    ignoreNamedArgument: true
    ignoreEnums: true
    ignoreRanges: true
    ignoreAnnotated: ['Composable']
  ForbiddenComment:
    active: false

comments:
  active: false

performance:
  active: true

potential-bugs:
  active: true
