name: Release Internal

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  release:
    name: Build and Release to Google Play Internal
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Decode keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > release.keystore

      - name: Build release bundle
        env:
          KEYSTORE_FILE: ../release.keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_ALIAS_PASSWORD: ${{ secrets.KEY_ALIAS_PASSWORD }}
        run: ./gradlew bundleRelease

      - name: Upload to Google Play Internal
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_JSON_KEY }}
          packageName: com.eurotax.supplylens
          releaseFiles: app/build/outputs/bundle/prodRelease/app-prod-release.aab
          track: internal
          status: completed

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: app/build/outputs/bundle/prodRelease/app-prod-release.aab
          retention-days: 30

      - name: Clean up keystore
        if: always()
        run: rm -f release.keystore
